// Le Petit Jaguar — the game's strings (fr / es / en). The title lives in meta.js.
export default {
  fr: {
    'jaguar.path': 'Aide le petit jaguar à retrouver son papa ! Glisse le jaguar.',
    'jaguar.chooseLevel': 'Choisis un niveau.',
    'jaguar.level': 'Niveau {n}',
    'jaguar.jaguar': 'Petit jaguar',
    'jaguar.board': 'Labyrinthe',
    'jaguar.continue': 'Continuer',
    'jaguar.levelDone': 'Bravo ! Le petit jaguar est avec son papa !',
    'jaguar.sniff': 'Hmm… Papa appelle !',
    'jaguar.clue': 'Suis les traces de pattes !',
    'jaguar.glow': 'Les traces montrent le chemin !',
    'jaguar.hug': 'Un gros câlin !',
  },
  es: {
    'jaguar.path': '¡Ayuda al pequeño jaguar a encontrar a su papá! Desliza el jaguar.',
    'jaguar.chooseLevel': 'Elige un nivel.',
    'jaguar.level': 'Nivel {n}',
    'jaguar.jaguar': 'Pequeño jaguar',
    'jaguar.board': 'Laberinto',
    'jaguar.continue': 'Continuar',
    'jaguar.levelDone': '¡Bravo! ¡El pequeño jaguar está con su papá!',
    'jaguar.sniff': 'Mmm… ¡Papá llama!',
    'jaguar.clue': '¡Sigue las huellas!',
    'jaguar.glow': '¡Las huellas muestran el camino!',
    'jaguar.hug': '¡Un abrazo grande!',
  },
  en: {
    'jaguar.path': 'Help the little jaguar find its papa! Slide the jaguar.',
    'jaguar.chooseLevel': 'Choose a level.',
    'jaguar.level': 'Level {n}',
    'jaguar.jaguar': 'Little jaguar',
    'jaguar.board': 'Maze',
    'jaguar.continue': 'Continue',
    'jaguar.levelDone': 'Well done! The little jaguar is with its papa!',
    'jaguar.sniff': 'Hmm… Papa is calling!',
    'jaguar.clue': 'Follow the paw prints!',
    'jaguar.glow': 'The paw prints show the way!',
    'jaguar.hug': 'A big hug!',
  },
};
